fun main(){

    println("Enter number 1:")
    var num1: Int = readln().toInt()
    println("-End of Code-")

//    var numbers = arrayOf<Int>(4,2,1)
//    println(numbers[3])
//
//    println(2/0)

}

//Exception
//- something that disrupts a normal flow of your code
// recoverable - you handle exceptions

//Error
// unrecoverable

//try - catch block